(part "50SEV330M12_5X13_5"
    (packageRef "CAPAE1275X1400N")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Rubycon")
    (property "Manufacturer_Part_Number" "50SEV330M12.5X13.5")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "CAP ALUM 330UF 20% 50V SMD")
    (property "Datasheet_Link" "https://www.rubycon.co.jp/wp-content/uploads/catalog-aluminum/SEV.pdf")
    (property "symbolName1" "50SEV330M12_5X13_5")
)
